version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - net_api
    ports:
      - 8085:8085
    env_file: .env

networks:
  net_api:


